# Generated by Django 5.1.2 on 2024-11-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageUsers', '0002_usr_alter_userprofile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
